export const pokemonList = [
    {
        name: 'Bulbasaur',
        generation: '1ª',
        types: ['Planta', 'Veneno'],
        description: 'Bulbasaur é um Pokémon de tipo Planta/Veneno, conhecido por ter uma semente em suas costas que cresce à medida que ele se desenvolve.',
    },
    {
        name: 'Ivysaur',
        generation: '1ª',
        types: ['Planta', 'Veneno'],
        description: 'Ivysaur é a evolução de Bulbasaur, com uma planta começando a crescer em suas costas, preparando-se para se tornar uma enorme flor.',
    },
    {
        name: 'Venusaur',
        generation: '1ª',
        types: ['Planta', 'Veneno'],
        description: 'Venusaur é a forma final de Bulbasaur, com uma grande flor em suas costas que pode liberar um cheiro forte.',
    },
    {
        name: 'Charmander',
        generation: '1ª',
        types: ['Fogo'],
        description: 'Charmander é um pokémon com chamas na cauda que queimam quando ele está irritado.',
    },
    {
        name: 'Charmeleon',
        generation: '1ª',
        types: ['Fogo'],
        description: 'Charmeleon é a evolução de Charmander, com chamas intensas que queimam quando ele está irritado.',
    },
    {
        name: 'Charizard',
        generation: '1ª',
        types: ['Fogo', 'Voador'],
        description: 'Charizard é a forma final de Charmander, um Pokémon de tipo Fogo/Voando, com a capacidade de soltar chamas poderosas.',
    },
    {
        name: 'Squirtle',
        generation: '1ª',
        types: ['Água'],
        description: 'Squirtle é um Pokémon de tipo Água, conhecido por sua habilidade em disparar jatos d\'água com grande força.',
    },
    {
        name: 'Wartortle',
        generation: '1ª',
        types: ['Água'],
        description: 'Wartortle é a evolução de Squirtle, com uma cauda peluda e uma postura mais agressiva.',
    },
    {
        name: 'Blastoise',
        generation: '1ª',
        types: ['Água'],
        description: 'Blastoise é a forma final de Squirtle, com canhões de água poderosos em seus ombros, usados para atacar seus inimigos.',
    },
    {
        name: 'Caterpie',
        generation: '1ª',
        types: ['Inseto'],
        description: 'Caterpie é um Pokémon do tipo Inseto, conhecido por ser a primeira forma de evolução no seu caminho até Metapod e Butterfree.',
    },
    {
        name: 'Metapod',
        generation: '1ª',
        types: ['Inseto'],
        description: 'Metapod é a forma intermediária de Caterpie, uma casca dura que protege a crisálida enquanto ele se prepara para se transformar em Butterfree.',
    },
    {
        name: 'Butterfree',
        generation: '1ª',
        types: ['Inseto', 'Voador'],
        description: 'Butterfree é a forma final de Caterpie, um Pokémon do tipo Inseto/Voador que usa suas asas para voar e lançar poderosos ataques de pó.',
    },
    {
        name: 'Weedle',
        generation: '1ª',
        types: ['Inseto', 'Veneno'],
        description: 'Weedle é um Pokémon do tipo Inseto/Veneno, conhecido por seu ferrão venenoso na cauda.',
    },
    {
        name: 'Kakuna',
        generation: '1ª',
        types: ['Inseto', 'Veneno'],
        description: 'Kakuna é a forma evolutiva intermediária de Weedle, com uma casca dura que o protege enquanto ele se transforma em Beedrill.',
    },
    {
        name: 'Beedrill',
        generation: '1ª',
        types: ['Inseto', 'Veneno'],
        description: 'Beedrill é a forma final de Weedle, um Pokémon do tipo Inseto/Veneno com poderosos ferrões em suas mãos e cauda.',
    },
    {
        name: 'Pidgey',
        generation: '1ª',
        types: ['Normal', 'Voador'],
        description: 'Pidgey é um Pokémon do tipo Normal/Voador, encontrado em várias áreas. É um dos Pokémon mais comuns da região.',
    },
    {
        name: 'Pidgeotto',
        generation: '1ª',
        types: ['Normal', 'Voador'],
        description: 'Pidgeotto é a evolução de Pidgey. Mais forte e agressivo, ele usa suas asas poderosas para atacar.',
    },
    {
        name: 'Pidgeot',
        generation: '1ª',
        types: ['Normal', 'Voador'],
        description: 'Pidgeot é a forma final de Pidgey, com impressionantes asas que podem criar ventos fortes e usar ataques poderosos.',
    },
    {
        name: 'Rattata',
        generation: '1ª',
        types: ['Normal'],
        description: 'Rattata é um Pokémon rápido do tipo Normal, conhecido por sua habilidade de correr a grandes velocidades e atacar rapidamente.',
    },
    {
        name: 'Raticate',
        generation: '1ª',
        types: ['Normal'],
        description: 'Raticate é a evolução de Rattata, com dentes afiados e uma habilidade para atacar de forma agressiva.',
    },
    {
        name: 'Spearow',
        generation: '1ª',
        types: ['Normal', 'Voador'],
        description: 'Spearow é um Pokémon agressivo do tipo Normal/Voador, que ataca em bandos e usa seu bico afiado.',
    },
    {
        name: 'Fearow',
        generation: '1ª',
        types: ['Normal', 'Voador'],
        description: 'Fearow é a evolução de Spearow, com um bico mais forte e a habilidade de voar a grandes altitudes.',
    },
    {
        name: 'Ekans',
        generation: '1ª',
        types: ['Veneno'],
        description: 'Ekans é um Pokémon do tipo Veneno, conhecido por sua habilidade de se esgueirar e atacar com rapidez.',
    },
    {
        name: 'Arbok',
        generation: '1ª',
        types: ['Veneno'],
        description: 'Arbok é a evolução de Ekans, com uma poderosa cobra de veneno e uma enorme capacidade de intimidar seus oponentes.',
    },
    {
        name: 'Pikachu',
        generation: '1ª',
        types: ['Elétrico'],
        description: 'Pikachu é um Pokémon elétrico famoso e o mascote da franquia Pokémon. Ele tem a habilidade de gerar eletricidade.',
    },
    {
        name: 'Raichu',
        generation: '1ª',
        types: ['Elétrico'],
        description: 'Raichu é a evolução de Pikachu, com mais energia elétrica e um poder maior de gerar eletricidade.',
    },
    {
        name: 'Sandshrew',
        generation: '1ª',
        types: ['Terra'],
        description: 'Sandshrew é um Pokémon do tipo Terra, conhecido por se entocar na terra e escavar buracos.',
    },
    {
        name: 'Sandslash',
        generation: '1ª',
        types: ['Terra'],
        description: 'Sandslash é a evolução de Sandshrew, com garras afiadas e uma habilidade em escavar com rapidez.',
    },
    {
        name: 'Nidoran-m',
        generation: '1ª',
        types: ['Veneno'],
        description: 'Nidoran♀ é um Pokémon do tipo Veneno, conhecido por sua natureza defensiva e habilidades de ataque com veneno.',
    },
    {
        name: 'Nidorina',
        generation: '1ª',
        types: ['Veneno'],
        description: 'Nidorina é a evolução de Nidoran♀, mais forte e capaz de se defender melhor contra os inimigos.',
    },
    {
        name: 'Nidoqueen',
        generation: '1ª',
        types: ['Veneno', 'Terra'],
        description: 'Nidoqueen é a forma final de Nidoran♀, com um corpo forte e resistente, com habilidades de defesa e ataque.',
    },
    {
        name: 'Nidoran-f',
        generation: '1ª',
        types: ['Veneno'],
        description: 'Nidoran♂ é um Pokémon do tipo Veneno, com espinhos e uma natureza mais agressiva.',
    },
    {
        name: 'Nidorino',
        generation: '1ª',
        types: ['Veneno'],
        description: 'Nidorino é a evolução de Nidoran♂, mais forte e com espinhos afiados para lutar.',
    },
    {
        name: 'Nidoking',
        generation: '1ª',
        types: ['Veneno', 'Terra'],
        description: 'Nidoking é a forma final de Nidoran♂, poderoso e com um grande poder de ataque físico e habilidades de veneno.',
    },
    {
        name: 'Clefairy',
        generation: '1ª',
        types: ['Fada'],
        description: 'Clefairy é um Pokémon do tipo Fada, conhecido por sua habilidade de dançar ao luar e usar poderes místicos.',
    },
    {
        name: 'Clefable',
        generation: '1ª',
        types: ['Fada'],
        description: 'Clefable é a evolução de Clefairy, com mais poder mágico e habilidades de cura.',
    },
];
